name: CI
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Generate layout.json
        run: |
          cd ./A32NX
          python3 build.py
      - uses: actions/upload-artifact@v2
        with:
          name: A32NX-master
          path: ./A32NX/
      - name: Commit changes
        run: |
          ./.github/workflows/commit_layout_changes.sh
